# Generated by Django 5.1.6 on 2025-03-28 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=510)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='subscription/')),
                ('providers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='LicenseTrack.providers')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='LicenseTrack.users')),
            ],
        ),
        migrations.CreateModel(
            name='Renewals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(editable=False)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_no', models.CharField(max_length=10, unique=True)),
                ('receipt', models.FileField(upload_to='receipt/')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='LicenseTrack.subscription')),
            ],
        ),
    ]
