# Generated by Django 5.1.6 on 2025-03-11 08:27

import LicenseTrack.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_license', models.CharField(choices=[('Subscription', 'Subscription'), ('Perpetual', 'Perpetual')], max_length=100)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('expiry_date', models.DateField(default=LicenseTrack.models.default_expiry_date)),
                ('reminder_days', models.JSONField(default=LicenseTrack.models.default_reminder_days)),
                ('document', models.FileField(upload_to='software/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renew_date', models.DateField()),
                ('renew_status', models.CharField(choices=[('expired', 'Expired'), ('active', 'Active'), ('renewed', 'Renewed')], max_length=20)),
                ('renew_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renew', to='LicenseTrack.software')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('Expiry', 'Expiry'), ('Renewal Reminder', 'Renewal Reminder')], max_length=100)),
                ('date_notification', models.DateField(auto_now_add=True)),
                ('sent_notification', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='LicenseTrack.software')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='LicenseTrack.user_profile')),
            ],
        ),
    ]
