# Generated by Django 5.1.6 on 2025-04-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTrack', '0002_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='subscription/'),
        ),
    ]
